/*
 Navicat Premium Data Transfer

 Source Server         : postgre 186
 Source Server Type    : PostgreSQL
 Source Server Version : 100021
 Source Host           : 186.150.200.131:5432
 Source Catalog        : syplans
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100021
 File Encoding         : 65001

 Date: 25/07/2022 14:55:56
*/


-- ----------------------------
-- Table structure for eje_estrategico
-- ----------------------------
DROP TABLE IF EXISTS "public"."eje_estrategico";
CREATE TABLE "public"."eje_estrategico" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "no_orden" int4,
  "nombre" varchar(255) COLLATE "pg_catalog"."default",
  "descripcion" text COLLATE "pg_catalog"."default",
  "aliniacion_end" int4,
  "aliniacion_pnpsp" int4,
  "aliniacion_ods" int4,
  "pei" int4,
  "created_at" timestamp(6),
  "updated_at" timestamp(6),
  "deleted_at" timestamp(6),
  "created_by" int4,
  "updated_by" int4,
  "deleted_by" int4
)
;

-- ----------------------------
-- Primary Key structure for table eje_estrategico
-- ----------------------------
ALTER TABLE "public"."eje_estrategico" ADD CONSTRAINT "eje_estrategico_pkey" PRIMARY KEY ("id");
