ALTER TABLE "public"."auditoria_programa_plan_proceso" ADD COLUMN "usuario" int2;

CREATE TABLE "public"."iso_estructura" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "secuencia" int4,
  "nombre" varchar(255) COLLATE "pg_catalog"."default",
  "descripcion" varchar(255) COLLATE "pg_catalog"."default",
  "normativo" varchar(255) COLLATE "pg_catalog"."default",
  "compania" int4,
  "institucion" int4,
  "tempid" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "iso_estructura_pkey" PRIMARY KEY ("id")
)
;

CREATE TABLE "public"."iso_normativos" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "secuencia" int4,
  "nombre" varchar(255) COLLATE "pg_catalog"."default",
  "descripcion" varchar(255) COLLATE "pg_catalog"."default",
  "compania" int4,
  "institucion" int4,
  CONSTRAINT "iso_normativos_pkey" PRIMARY KEY ("id")
)
;

CREATE TABLE "public"."proceso_estructura_iso" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "proceso" int4,
  "estructura" int4
)
;